### ISSUE TITLE
Entities aren't always removed when closing game

### ISSUE THREAD

**Issue by hYdos** [NucleoidMC/plasmid#3]

**Comment by hYdos** [comment]
when i figure out where this happens ill work on a fix.

**Comment by hYdos** [comment]
the most affected game modes for this would be bedwars and castle wars

**Comment by gegy1000** [comment]
Not totally sure how to approach this- main issue is the global entity lists that are stored on the world instance. We're causing chunks to reload themselves, but the entity is still in the global list so it stays. Also worth nothing that there are probably similar issues caused by state like this- namely block entities but there may be others too.
